# name: Fetch Track Lyrics

# on:
#   schedule:
#     - cron: "0 */2 * * *"
#   workflow_dispatch:

# jobs:
#   update-tracks:
#     runs-on: ubuntu-latest
#     timeout-minutes: 20 # Set the job timeout to 20 minutes

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: "3.x"

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pymongo spotipy python-dotenv

#       - name: Fetch Lyrics Job
#         env:
#           SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
#           SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
#           SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
#           SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
#           MONGO_URL: ${{ secrets.MONGO_URL }}
#         run: |
#           python app/jobs/fetch_lyrics.py
